# .github/checkov/aws/custom_rules/CKV_CUSTOM_1.yaml
metadata:
  id: "CKV_CUSTOM_1"
  name: "Ensure RDS PostgreSQL instances have pgaudit activated"
  description: "Checks if RDS PostgreSQL instances have pgaudit enabled via their parameter group."
  scope:
    provider: aws
  category: Logging
  severity: HIGH

definition:
  and:
    - resource_types:
        - aws_db_instance
    - attribute: engine
      operator: equals
      value: "postgres"
    - attribute: parameter_group_name
      operator: not_null
    - connected_resources:
        resource_type: aws_db_parameter_group
        association_attribute: parameter_group_name
        condition:
          attribute: "parameters[?name=='shared_preload_libraries'].value | [0]"
          operator: contains
          value: "pgaudit"
