metadata:
  id: "CKV_CUSTOM_2"
  name: "Ensure RDS PostgreSQL instances have pgaudit activated"
  description: "Checks if RDS PostgreSQL instances have pgaudit enabled via their parameter group."
  scope:
    provider: aws
  categories:
    - logging
    - compliance
  severity: HIGH

definition:
  and:
    - cond_type: resource
      resource_types:
        - aws_db_instance
    - attribute: engine
      operator: equals
      value: "postgres"
    - attribute: parameter_group_name
      operator: not_null
    - connected_resources:
        # Assuming the parameter group is defined in the same Terraform code
        resource_type: aws_db_parameter_group
        association_attribute: parameter_group_name
        condition:
          and:
            - attribute: parameters[?name=='shared_preload_libraries'].value | [0]
              operator: contains
              value: "pgaudit"
      
