metadata:
  id: "CKV_CUSTOM_1"
  name: "Ensure RDS has connection, disconnection logs enabled and pgaudit enabled"
  category: "Logging and Auditing"
  severity: "HIGH"
  description: |
    Ensures that every AWS RDS instance has connection and disconnection logging enabled
    and the pgaudit extension enabled for enhanced auditing capabilities.

definition:
  and:
    - cond_type: "attribute"
      resource_types:
        - "aws_db_instance"
      attribute: "enabled_cloudwatch_logs_exports"
      operator: "contains"
      value: "connection"

    - cond_type: "attribute"
      resource_types:
        - "aws_db_instance"
      attribute: "enabled_cloudwatch_logs_exports"
      operator: "contains"
      value: "disconnection"

    - cond_type: "attribute"
      resource_types:
        - "aws_db_instance"
      attribute: "parameter_group_name"
      operator: "regex_match"
      value: ".*pgaudit.*"
