name: CI
on:
  push:
    branches: [ "dev" ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Read controls from file
        id: read_controls
        run: |
          controls=$(cat .checkov/controls.txt | tr '\n' ',')
          echo "::set-output name=controls::$controls"

      - name: Run Checkov
        run: |
          checkov -d ./infra --check ${{ steps.read_controls.outputs.controls }} -o json
