name: Static Analysis Pipeline

on:
  push:
    branches-ignore:
      - main
permissions:
  contents: write
  security-events: write  # Ensure the action can upload SARIF results 


jobs:
  
  tflint:
    runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache TFLint plugin directory
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint and generate SARIF report
        run: |
          tflint -f sarif --chdir=infra/ --recursive > tflint.sarif
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tflint.sarif
          category: tflint

      - name: Install Gitleaks 
        run: |
          curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest | grep "browser_download_url.*linux.*tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -qi -
          tar -xzf gitleaks*.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: gitleaks detect --source . --verbose