name: Static Analysis Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read     

jobs:
  set_commit_flags:
    name: 'Set Commit Flags'
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.check_commit_message.outputs.should_run }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Commit Message
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -iq "si ci/cd"; then
            echo "::set-output name=should_run::true"
          else
            echo "::set-output name=should_run::false"
          fi

  static_analysis:
    name: 'Static Analysis'
    runs-on: ubuntu-latest
    needs: set_commit_flags
    if: |
      startsWith(github.ref, 'refs/heads/dev') &&
      needs.set_commit_flags.outputs.should_run == 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint

      - name: Set Security Checks Variable
        id: set_security_checks
        run: |
          SECURITY_CHECKS=$(paste -sd, .github/checkov/security_checks.txt)
          echo "SECURITY_CHECKS=${SECURITY_CHECKS}" >> $GITHUB_ENV
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov security Checks
        id: run_checkov
        run: |
          checkov -d ./infra --check ${{ env.SECURITY_CHECKS }} --external-checks-dir .github/checkov --skip-framework terraform
      
      - name: Run Checkov Custom Checks
        id: run_checkov_custom
        run: |
          checkov -d ./infra --external-checks-dir .github/checkov/custom_rules --skip-framework terraform

      - name: Run Checkov Green IT
        id: run_checkov_greenit
        run: |
          checkov -d ./infra --external-checks-dir .github/checkov/green_it --skip-framework terraform