# .github/workflows/static-analysis.yml

name: Static Analysis Pipeline

on:
  push:
    branches:
      - "**"           # Trigger on push to any branch
    branches-ignore:
      - main           # Except the main branch

permissions:
  contents: read      # Required for actions/checkout

jobs:
  static_analysis:
    name: 'Static Analysis'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Check Commit Message for 'si ci/cd'
      - name: Check Commit Message
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -iq "si ci/cd"; then
            echo "Commit message contains 'si ci/cd'. Proceeding with Static Analysis."
            echo "should_run=true" >> $GITHUB_ENV
          else
            echo "Commit message does not contain 'si ci/cd'. Skipping Static Analysis."
            echo "should_run=false" >> $GITHUB_ENV
          fi

  # Static Analysis Job
  static_analysis:
    name: 'Static Analysis'
    runs-on: ubuntu-latest
    needs: set_commit_flags
    if: |
      startsWith(github.ref, 'refs/heads/dev') &&
      env.has_si_ci_cd == 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint

      - name: Set Security Checks Variable
        id: set_security_checks
        run: |
          SECURITY_CHECKS=$(paste -sd, .github/checkov/security_checks.txt)
          echo "SECURITY_CHECKS=${SECURITY_CHECKS}" >> $GITHUB_ENV

      - name: Run Checkov Static Analysis
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          args: --check ${{ env.SECURITY_CHECKS }} --external-checks-dir .github/checkov --skip-framework terraform