#https://spacelift.io/blog/infrastructure-as-code-with-github-actions

name: Static Analysis Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write     

jobs:
  set_commit_flags:
    name: 'Set Commit Flags'
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.check_commit_message.outputs.should_run }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Commit Message
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -iq "si ci"; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
          
  static_analysis:
    name: 'Static Analysis'
    runs-on: ubuntu-latest
    needs: set_commit_flags

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Checkov PRISMA Policies
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          config_file: aws/CKV_LIST.yaml
          output_format: csv
          output_file_path: .
        continue-on-error: true

      - name: Run Checkov CUSTOM Policies
        id: checkov_custom
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          external_checks_dirs: aws/custom_rules
          config_file: aws/CKV_CUSTOM_LIST.yaml
          output_format: csv
          output_file_path: .
        continue-on-error: true

      - name: Run Checkov GREEN IT Policies
        id: checkov_greenit
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          external_checks_dirs: aws/custom_rules
          config_file: aws/CKV_GREEN_LIST.yaml
          output_format: csv
          output_file_path: .
        continue-on-error: true

      - name: Run Python Script
        run: |
          python3 staticResults.py  # Ensure your script is named script.py and located in the root directory
      
      - name: Add commit comment
        run: |
          ls -lias
          file_content=$(cat failed_CKV.txt)
          jq -nc --arg body "$file_content" '{"body": $body}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
      
      
      - name: Upload Checkov Reports
        uses: actions/upload-artifact@v3
        with:
          name: all-reports
          path: |
            *.csv
            failed_CKV.txt
            failed_CKV_Detailed.txt
  



