name: Static Analysis Pipeline

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read     

jobs:
  set_commit_flags:
    name: 'Set Commit Flags'
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.check_commit_message.outputs.should_run }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Commit Message
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -iq "si ci"; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
          
  static_analysis:
    name: 'Static Analysis'
    runs-on: ubuntu-latest
    needs: set_commit_flags

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          config_file: aws/CKV_LIST.yaml
          output_format: csv
          output_file_path: checkov_check.json
        continue-on-error: true

      - name: Run Checkov
        id: checkov_custom
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          external_checks_dirs: aws/custom_rules
          config_file: aws/CKV_CUSTOM_LIST.yaml
          output_format: csv
          output_file_path: checkov_custom.json
        continue-on-error: true

      - name: Run Checkov
        id: checkov_greenit
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          external_checks_dirs: aws/custom_rules
          config_file: aws/CKV_GREEN_LIST.yaml
          output_format: csv
          output_file_path: checkov_greenit.json
        continue-on-error: true

      

      - name: Upload Checkov Green IT JSON Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov_check.json
          path: checkov_check.json

      - name: Upload Checkov Green IT JSON Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov_custom.json
          path: checkov_custom.json

      - name: Upload Checkov Green IT JSON Report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-greenit.json
          path: checkov_greenit.json

